/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CliAuthRouteImport } from './routes/cli-auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgOrgSlugRouteImport } from './routes/org/$orgSlug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as OrgOrgSlugIndexRouteImport } from './routes/org/$orgSlug/index'
import { Route as OrgOrgSlugSettingsMembersRouteImport } from './routes/org/$orgSlug/settings/members'
import { Route as OrgOrgSlugSettingsBillingRouteImport } from './routes/org/$orgSlug/settings/billing'
import { Route as OrgOrgSlugSettingsAuditLogRouteImport } from './routes/org/$orgSlug/settings/audit-log'
import { Route as OrgOrgSlugProjectsProjectSlugRouteImport } from './routes/org/$orgSlug/projects/$projectSlug'
import { Route as OrgOrgSlugProjectsProjectSlugIndexRouteImport } from './routes/org/$orgSlug/projects/$projectSlug/index'
import { Route as OrgOrgSlugProjectsProjectSlugSecretsRouteImport } from './routes/org/$orgSlug/projects/$projectSlug/secrets'

const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthRoute = CliAuthRouteImport.update({
  id: '/cli-auth',
  path: '/cli-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgSlugRoute = OrgOrgSlugRouteImport.update({
  id: '/org/$orgSlug',
  path: '/org/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgOrgSlugIndexRoute = OrgOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgOrgSlugRoute,
} as any)
const OrgOrgSlugSettingsMembersRoute =
  OrgOrgSlugSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => OrgOrgSlugRoute,
  } as any)
const OrgOrgSlugSettingsBillingRoute =
  OrgOrgSlugSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => OrgOrgSlugRoute,
  } as any)
const OrgOrgSlugSettingsAuditLogRoute =
  OrgOrgSlugSettingsAuditLogRouteImport.update({
    id: '/settings/audit-log',
    path: '/settings/audit-log',
    getParentRoute: () => OrgOrgSlugRoute,
  } as any)
const OrgOrgSlugProjectsProjectSlugRoute =
  OrgOrgSlugProjectsProjectSlugRouteImport.update({
    id: '/projects/$projectSlug',
    path: '/projects/$projectSlug',
    getParentRoute: () => OrgOrgSlugRoute,
  } as any)
const OrgOrgSlugProjectsProjectSlugIndexRoute =
  OrgOrgSlugProjectsProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrgOrgSlugProjectsProjectSlugRoute,
  } as any)
const OrgOrgSlugProjectsProjectSlugSecretsRoute =
  OrgOrgSlugProjectsProjectSlugSecretsRouteImport.update({
    id: '/secrets',
    path: '/secrets',
    getParentRoute: () => OrgOrgSlugProjectsProjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cli-auth': typeof CliAuthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/sandbox': typeof SandboxRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/org/$orgSlug': typeof OrgOrgSlugRouteWithChildren
  '/org/$orgSlug/': typeof OrgOrgSlugIndexRoute
  '/org/$orgSlug/projects/$projectSlug': typeof OrgOrgSlugProjectsProjectSlugRouteWithChildren
  '/org/$orgSlug/settings/audit-log': typeof OrgOrgSlugSettingsAuditLogRoute
  '/org/$orgSlug/settings/billing': typeof OrgOrgSlugSettingsBillingRoute
  '/org/$orgSlug/settings/members': typeof OrgOrgSlugSettingsMembersRoute
  '/org/$orgSlug/projects/$projectSlug/secrets': typeof OrgOrgSlugProjectsProjectSlugSecretsRoute
  '/org/$orgSlug/projects/$projectSlug/': typeof OrgOrgSlugProjectsProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cli-auth': typeof CliAuthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/sandbox': typeof SandboxRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/org/$orgSlug': typeof OrgOrgSlugIndexRoute
  '/org/$orgSlug/settings/audit-log': typeof OrgOrgSlugSettingsAuditLogRoute
  '/org/$orgSlug/settings/billing': typeof OrgOrgSlugSettingsBillingRoute
  '/org/$orgSlug/settings/members': typeof OrgOrgSlugSettingsMembersRoute
  '/org/$orgSlug/projects/$projectSlug/secrets': typeof OrgOrgSlugProjectsProjectSlugSecretsRoute
  '/org/$orgSlug/projects/$projectSlug': typeof OrgOrgSlugProjectsProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cli-auth': typeof CliAuthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/sandbox': typeof SandboxRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/org/$orgSlug': typeof OrgOrgSlugRouteWithChildren
  '/org/$orgSlug/': typeof OrgOrgSlugIndexRoute
  '/org/$orgSlug/projects/$projectSlug': typeof OrgOrgSlugProjectsProjectSlugRouteWithChildren
  '/org/$orgSlug/settings/audit-log': typeof OrgOrgSlugSettingsAuditLogRoute
  '/org/$orgSlug/settings/billing': typeof OrgOrgSlugSettingsBillingRoute
  '/org/$orgSlug/settings/members': typeof OrgOrgSlugSettingsMembersRoute
  '/org/$orgSlug/projects/$projectSlug/secrets': typeof OrgOrgSlugProjectsProjectSlugSecretsRoute
  '/org/$orgSlug/projects/$projectSlug/': typeof OrgOrgSlugProjectsProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cli-auth'
    | '/login'
    | '/onboarding'
    | '/sandbox'
    | '/accept-invitation/$invitationId'
    | '/auth/callback'
    | '/org/$orgSlug'
    | '/org/$orgSlug/'
    | '/org/$orgSlug/projects/$projectSlug'
    | '/org/$orgSlug/settings/audit-log'
    | '/org/$orgSlug/settings/billing'
    | '/org/$orgSlug/settings/members'
    | '/org/$orgSlug/projects/$projectSlug/secrets'
    | '/org/$orgSlug/projects/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cli-auth'
    | '/login'
    | '/onboarding'
    | '/sandbox'
    | '/accept-invitation/$invitationId'
    | '/auth/callback'
    | '/org/$orgSlug'
    | '/org/$orgSlug/settings/audit-log'
    | '/org/$orgSlug/settings/billing'
    | '/org/$orgSlug/settings/members'
    | '/org/$orgSlug/projects/$projectSlug/secrets'
    | '/org/$orgSlug/projects/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/cli-auth'
    | '/login'
    | '/onboarding'
    | '/sandbox'
    | '/accept-invitation/$invitationId'
    | '/auth/callback'
    | '/org/$orgSlug'
    | '/org/$orgSlug/'
    | '/org/$orgSlug/projects/$projectSlug'
    | '/org/$orgSlug/settings/audit-log'
    | '/org/$orgSlug/settings/billing'
    | '/org/$orgSlug/settings/members'
    | '/org/$orgSlug/projects/$projectSlug/secrets'
    | '/org/$orgSlug/projects/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliAuthRoute: typeof CliAuthRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SandboxRoute: typeof SandboxRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  OrgOrgSlugRoute: typeof OrgOrgSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-auth': {
      id: '/cli-auth'
      path: '/cli-auth'
      fullPath: '/cli-auth'
      preLoaderRoute: typeof CliAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgSlug': {
      id: '/org/$orgSlug'
      path: '/org/$orgSlug'
      fullPath: '/org/$orgSlug'
      preLoaderRoute: typeof OrgOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgSlug/': {
      id: '/org/$orgSlug/'
      path: '/'
      fullPath: '/org/$orgSlug/'
      preLoaderRoute: typeof OrgOrgSlugIndexRouteImport
      parentRoute: typeof OrgOrgSlugRoute
    }
    '/org/$orgSlug/settings/members': {
      id: '/org/$orgSlug/settings/members'
      path: '/settings/members'
      fullPath: '/org/$orgSlug/settings/members'
      preLoaderRoute: typeof OrgOrgSlugSettingsMembersRouteImport
      parentRoute: typeof OrgOrgSlugRoute
    }
    '/org/$orgSlug/settings/billing': {
      id: '/org/$orgSlug/settings/billing'
      path: '/settings/billing'
      fullPath: '/org/$orgSlug/settings/billing'
      preLoaderRoute: typeof OrgOrgSlugSettingsBillingRouteImport
      parentRoute: typeof OrgOrgSlugRoute
    }
    '/org/$orgSlug/settings/audit-log': {
      id: '/org/$orgSlug/settings/audit-log'
      path: '/settings/audit-log'
      fullPath: '/org/$orgSlug/settings/audit-log'
      preLoaderRoute: typeof OrgOrgSlugSettingsAuditLogRouteImport
      parentRoute: typeof OrgOrgSlugRoute
    }
    '/org/$orgSlug/projects/$projectSlug': {
      id: '/org/$orgSlug/projects/$projectSlug'
      path: '/projects/$projectSlug'
      fullPath: '/org/$orgSlug/projects/$projectSlug'
      preLoaderRoute: typeof OrgOrgSlugProjectsProjectSlugRouteImport
      parentRoute: typeof OrgOrgSlugRoute
    }
    '/org/$orgSlug/projects/$projectSlug/': {
      id: '/org/$orgSlug/projects/$projectSlug/'
      path: '/'
      fullPath: '/org/$orgSlug/projects/$projectSlug/'
      preLoaderRoute: typeof OrgOrgSlugProjectsProjectSlugIndexRouteImport
      parentRoute: typeof OrgOrgSlugProjectsProjectSlugRoute
    }
    '/org/$orgSlug/projects/$projectSlug/secrets': {
      id: '/org/$orgSlug/projects/$projectSlug/secrets'
      path: '/secrets'
      fullPath: '/org/$orgSlug/projects/$projectSlug/secrets'
      preLoaderRoute: typeof OrgOrgSlugProjectsProjectSlugSecretsRouteImport
      parentRoute: typeof OrgOrgSlugProjectsProjectSlugRoute
    }
  }
}

interface OrgOrgSlugProjectsProjectSlugRouteChildren {
  OrgOrgSlugProjectsProjectSlugSecretsRoute: typeof OrgOrgSlugProjectsProjectSlugSecretsRoute
  OrgOrgSlugProjectsProjectSlugIndexRoute: typeof OrgOrgSlugProjectsProjectSlugIndexRoute
}

const OrgOrgSlugProjectsProjectSlugRouteChildren: OrgOrgSlugProjectsProjectSlugRouteChildren =
  {
    OrgOrgSlugProjectsProjectSlugSecretsRoute:
      OrgOrgSlugProjectsProjectSlugSecretsRoute,
    OrgOrgSlugProjectsProjectSlugIndexRoute:
      OrgOrgSlugProjectsProjectSlugIndexRoute,
  }

const OrgOrgSlugProjectsProjectSlugRouteWithChildren =
  OrgOrgSlugProjectsProjectSlugRoute._addFileChildren(
    OrgOrgSlugProjectsProjectSlugRouteChildren,
  )

interface OrgOrgSlugRouteChildren {
  OrgOrgSlugIndexRoute: typeof OrgOrgSlugIndexRoute
  OrgOrgSlugProjectsProjectSlugRoute: typeof OrgOrgSlugProjectsProjectSlugRouteWithChildren
  OrgOrgSlugSettingsAuditLogRoute: typeof OrgOrgSlugSettingsAuditLogRoute
  OrgOrgSlugSettingsBillingRoute: typeof OrgOrgSlugSettingsBillingRoute
  OrgOrgSlugSettingsMembersRoute: typeof OrgOrgSlugSettingsMembersRoute
}

const OrgOrgSlugRouteChildren: OrgOrgSlugRouteChildren = {
  OrgOrgSlugIndexRoute: OrgOrgSlugIndexRoute,
  OrgOrgSlugProjectsProjectSlugRoute:
    OrgOrgSlugProjectsProjectSlugRouteWithChildren,
  OrgOrgSlugSettingsAuditLogRoute: OrgOrgSlugSettingsAuditLogRoute,
  OrgOrgSlugSettingsBillingRoute: OrgOrgSlugSettingsBillingRoute,
  OrgOrgSlugSettingsMembersRoute: OrgOrgSlugSettingsMembersRoute,
}

const OrgOrgSlugRouteWithChildren = OrgOrgSlugRoute._addFileChildren(
  OrgOrgSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliAuthRoute: CliAuthRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SandboxRoute: SandboxRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  OrgOrgSlugRoute: OrgOrgSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
