/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CliAuthRouteImport } from './routes/cli-auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardProjectSlugRouteImport } from './routes/dashboard/$projectSlug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardProjectSlugIndexRouteImport } from './routes/dashboard/$projectSlug/index'
import { Route as DashboardProjectSlugSettingsRouteImport } from './routes/dashboard/$projectSlug/settings'
import { Route as DashboardProjectSlugSecretsRouteImport } from './routes/dashboard/$projectSlug/secrets'
import { Route as DashboardProjectSlugMembersRouteImport } from './routes/dashboard/$projectSlug/members'
import { Route as DashboardProjectSlugAuditRouteImport } from './routes/dashboard/$projectSlug/audit'

const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthRoute = CliAuthRouteImport.update({
  id: '/cli-auth',
  path: '/cli-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectSlugRoute = DashboardProjectSlugRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectSlugIndexRoute =
  DashboardProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectSlugRoute,
  } as any)
const DashboardProjectSlugSettingsRoute =
  DashboardProjectSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectSlugRoute,
  } as any)
const DashboardProjectSlugSecretsRoute =
  DashboardProjectSlugSecretsRouteImport.update({
    id: '/secrets',
    path: '/secrets',
    getParentRoute: () => DashboardProjectSlugRoute,
  } as any)
const DashboardProjectSlugMembersRoute =
  DashboardProjectSlugMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => DashboardProjectSlugRoute,
  } as any)
const DashboardProjectSlugAuditRoute =
  DashboardProjectSlugAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => DashboardProjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cli-auth': typeof CliAuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/sandbox': typeof SandboxRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/$projectSlug': typeof DashboardProjectSlugRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$projectSlug/audit': typeof DashboardProjectSlugAuditRoute
  '/dashboard/$projectSlug/members': typeof DashboardProjectSlugMembersRoute
  '/dashboard/$projectSlug/secrets': typeof DashboardProjectSlugSecretsRoute
  '/dashboard/$projectSlug/settings': typeof DashboardProjectSlugSettingsRoute
  '/dashboard/$projectSlug/': typeof DashboardProjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cli-auth': typeof CliAuthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/sandbox': typeof SandboxRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/$projectSlug/audit': typeof DashboardProjectSlugAuditRoute
  '/dashboard/$projectSlug/members': typeof DashboardProjectSlugMembersRoute
  '/dashboard/$projectSlug/secrets': typeof DashboardProjectSlugSecretsRoute
  '/dashboard/$projectSlug/settings': typeof DashboardProjectSlugSettingsRoute
  '/dashboard/$projectSlug': typeof DashboardProjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cli-auth': typeof CliAuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/sandbox': typeof SandboxRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/$projectSlug': typeof DashboardProjectSlugRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/$projectSlug/audit': typeof DashboardProjectSlugAuditRoute
  '/dashboard/$projectSlug/members': typeof DashboardProjectSlugMembersRoute
  '/dashboard/$projectSlug/secrets': typeof DashboardProjectSlugSecretsRoute
  '/dashboard/$projectSlug/settings': typeof DashboardProjectSlugSettingsRoute
  '/dashboard/$projectSlug/': typeof DashboardProjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cli-auth'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/sandbox'
    | '/auth/callback'
    | '/dashboard/$projectSlug'
    | '/dashboard/'
    | '/dashboard/$projectSlug/audit'
    | '/dashboard/$projectSlug/members'
    | '/dashboard/$projectSlug/secrets'
    | '/dashboard/$projectSlug/settings'
    | '/dashboard/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cli-auth'
    | '/login'
    | '/onboarding'
    | '/sandbox'
    | '/auth/callback'
    | '/dashboard'
    | '/dashboard/$projectSlug/audit'
    | '/dashboard/$projectSlug/members'
    | '/dashboard/$projectSlug/secrets'
    | '/dashboard/$projectSlug/settings'
    | '/dashboard/$projectSlug'
  id:
    | '__root__'
    | '/'
    | '/cli-auth'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/sandbox'
    | '/auth/callback'
    | '/dashboard/$projectSlug'
    | '/dashboard/'
    | '/dashboard/$projectSlug/audit'
    | '/dashboard/$projectSlug/members'
    | '/dashboard/$projectSlug/secrets'
    | '/dashboard/$projectSlug/settings'
    | '/dashboard/$projectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CliAuthRoute: typeof CliAuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SandboxRoute: typeof SandboxRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli-auth': {
      id: '/cli-auth'
      path: '/cli-auth'
      fullPath: '/cli-auth'
      preLoaderRoute: typeof CliAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$projectSlug': {
      id: '/dashboard/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/dashboard/$projectSlug'
      preLoaderRoute: typeof DashboardProjectSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$projectSlug/': {
      id: '/dashboard/$projectSlug/'
      path: '/'
      fullPath: '/dashboard/$projectSlug/'
      preLoaderRoute: typeof DashboardProjectSlugIndexRouteImport
      parentRoute: typeof DashboardProjectSlugRoute
    }
    '/dashboard/$projectSlug/settings': {
      id: '/dashboard/$projectSlug/settings'
      path: '/settings'
      fullPath: '/dashboard/$projectSlug/settings'
      preLoaderRoute: typeof DashboardProjectSlugSettingsRouteImport
      parentRoute: typeof DashboardProjectSlugRoute
    }
    '/dashboard/$projectSlug/secrets': {
      id: '/dashboard/$projectSlug/secrets'
      path: '/secrets'
      fullPath: '/dashboard/$projectSlug/secrets'
      preLoaderRoute: typeof DashboardProjectSlugSecretsRouteImport
      parentRoute: typeof DashboardProjectSlugRoute
    }
    '/dashboard/$projectSlug/members': {
      id: '/dashboard/$projectSlug/members'
      path: '/members'
      fullPath: '/dashboard/$projectSlug/members'
      preLoaderRoute: typeof DashboardProjectSlugMembersRouteImport
      parentRoute: typeof DashboardProjectSlugRoute
    }
    '/dashboard/$projectSlug/audit': {
      id: '/dashboard/$projectSlug/audit'
      path: '/audit'
      fullPath: '/dashboard/$projectSlug/audit'
      preLoaderRoute: typeof DashboardProjectSlugAuditRouteImport
      parentRoute: typeof DashboardProjectSlugRoute
    }
  }
}

interface DashboardProjectSlugRouteChildren {
  DashboardProjectSlugAuditRoute: typeof DashboardProjectSlugAuditRoute
  DashboardProjectSlugMembersRoute: typeof DashboardProjectSlugMembersRoute
  DashboardProjectSlugSecretsRoute: typeof DashboardProjectSlugSecretsRoute
  DashboardProjectSlugSettingsRoute: typeof DashboardProjectSlugSettingsRoute
  DashboardProjectSlugIndexRoute: typeof DashboardProjectSlugIndexRoute
}

const DashboardProjectSlugRouteChildren: DashboardProjectSlugRouteChildren = {
  DashboardProjectSlugAuditRoute: DashboardProjectSlugAuditRoute,
  DashboardProjectSlugMembersRoute: DashboardProjectSlugMembersRoute,
  DashboardProjectSlugSecretsRoute: DashboardProjectSlugSecretsRoute,
  DashboardProjectSlugSettingsRoute: DashboardProjectSlugSettingsRoute,
  DashboardProjectSlugIndexRoute: DashboardProjectSlugIndexRoute,
}

const DashboardProjectSlugRouteWithChildren =
  DashboardProjectSlugRoute._addFileChildren(DashboardProjectSlugRouteChildren)

interface DashboardRouteChildren {
  DashboardProjectSlugRoute: typeof DashboardProjectSlugRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProjectSlugRoute: DashboardProjectSlugRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CliAuthRoute: CliAuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SandboxRoute: SandboxRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
